# Generated by Django 2.1.7 on 2019-03-26 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190326_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 18, 25, 8, 715160, tzinfo=utc), verbose_name='date published'),
        ),
    ]
